spring_profiles: postgresql

database:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://${DB_PORT_5432_TCP_ADDR}:${DB_PORT_5432_TCP_PORT}/${DB_ENV_DB}
  username: ${DB_ENV_USER:root}
  password: ${DB_ENV_PASS:changeme}

oauth:
  client:
    override: true
    autoapprove:
      - cloudbreak_shell
      - periscope-client
  clients:
    admin:
      id: admin
      secret: adminsecret
      authorized-grant-types: client_credentials
      scope: none
      authorities: uaa.admin,scim.write,scim.read,clients.read,clients.write,clients.secret
    uluwatu:
      id: uluwatu
      secret: uluwatusecret
      authorized-grant-types: authorization_code
      scope: cloudbreak.templates,cloudbreak.blueprints,cloudbreak.credentials,cloudbreak.stacks,openid,password.write
      authorities: uaa.none
      redirect-uri: http://localhost:3000/authorize
    cloudbreak:
      id: cloudbreak
      secret: cloudbreaksecret
      authorized-grant-types: client_credentials
      scope: scim.read,scim.write,password.write
      authorities: uaa.resource,scim.read,scim.write,password.write
    cloudbreak_shell:
      id: cloudbreak_shell
      authorized-grant-types: implicit
      scope: cloudbreak.templates,cloudbreak.blueprints,cloudbreak.credentials,cloudbreak.stacks,openid,password.write
      authorities: uaa.none
      redirect-uri: http://cloudbreak.shell
    periscope-client:
      id: periscope-client
      authorized-grant-types: implicit
      scope: cloudbreak.templates,cloudbreak.blueprints,cloudbreak.credentials,cloudbreak.stacks,openid,password.write
      authorities: uaa.none
      redirect-uri: http://periscope.client

scim:
  username_pattern: '[a-z0-9+\-_.@]+'
  users:
    - admin@sequenceiq.com|seqadmin|admin@sequenceiq.com|Default|User|openid,cloudbreak.templates,cloudbreak.blueprints,cloudbreak.credentials,cloudbreak.stacks,sequenceiq.cloudbreak.admin,sequenceiq.cloudbreak.user,sequenceiq.account.abcd1234.SequenceIQ
    - paul@sequenceiq.com|paul|paul@sequenceiq.com|Paul|Smith|openid,cloudbreak.templates,cloudbreak.blueprints,cloudbreak.credentials,cloudbreak.stacks,sequenceiq.cloudbreak.user,sequenceiq.account.abcd1234.SequenceIQ
